### ISSUE TITLE
Google Map Location - Location is not centered/visible after resizing the browser window

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/CKCS#10]
The map isn't scaling down properly and the pin point is not visible.

**Comment by ccmorris** [comment]
The map does not recenter itself when the browser size changes. Is this what you are referring to?

If you load the page with page width already sized to an iPad then it should be fine, but resizing the window is the real cause of what you are seeing. I think.

**Comment by ccmorris** [comment]
I have found a way to keep the map centered better while resizing the browser. This issue will be closed with the commit. You can reopen this is if this does not solve your problem or if I misunderstood.
